version: "3"

services:
  ph-frontend:
    image: polyhome/frontend:latest
    hostname: ph-frontend
    container_name: ph-frontend
    restart: unless-stopped
    environment:
      - API_URL=ph-backend:8421
    ports:
      - 8422:8422

  ph-backend:
    image: polyhome/backend:latest
    hostname: ph-backend
    container_name: ph-backend
    restart: unless-stopped
    environment:
      - MONGO_CONN_STRING=${MONGO_CONN_STRING}
    ports:
      - 8421:8421
    volumes:
      - ${PH_CONFIG}:/app/config

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:2017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
